npm_package_list:
  - {name: 'bower', state: 'latest'}
  - {name: 'yuglify', state: 'latest'}
  - {name: 'babel-cli', state: 'latest'}  
  - {name: 'webpack', state: 'latest'}
  - {name: 'grunt-cli', state: 'latest'}


